### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by m-kuhn** [infogrips/ilic#1]
Thanks for this interesting project.

What exactly is the role of
- the java dependency (antlr)
- and bin.zip inside the git

Is one an output of the other?
I can see that bin.zip contains some windows specific libraries, are there any (known) limitations to build these for other platforms?

Thanks for any inputs regarding this

**Comment by infogrips** [comment]
ANTLR is a parser generator written in Java. ANTLR is only used to produce .cpp source files from ANTLR .g4 and .l4 syntax definition files (see also /input/parser/grammar) at compile time. Java is not necessary at runtime.

The bin.zip archive contains the ANTLR runtime for Windows as static libraries. The .zip was (unfortunally) necessary, as GitHub does not allow files > 100 MBytes. Unzip the libraries before compiling the project.

Right now the project is in beta. We will release a first stable version for Windows by end of july. Other platforms (ie. MacOS, Debian, Ubuntu) will follow in august.

**Comment by m-kuhn** [comment]
Would it be possible to regenerate the antlr runtime as part of the compilation process to allow recompiling for any platform?

**Comment by infogrips** [comment]
As a stated before we concentrate our efforts right now on the Windows plattform. We will support other platforms in august 2021. The build process will then be adapted to support all platforms. The future build process will be based on .cpp sources only (no static libraries neccessary).

The cpp sources of the ANTLR runtime are available at https://github.com/antlr/antlr4/tree/master/runtime/Cpp.
You can compile them for any other platform.

**Comment by m-kuhn** [comment]
Thank you, excellent news.

**Comment by m-kuhn** [comment]
What is the current progress of the status for other platforms?
